Shining-Jicheon-Stars/yjg-dart-flutter-frontend

- lib/main.dart
- lib/screens/bus/bus_main.dart
- lib/screens/bus/bus_qr.dart
- lib/screens/salon/salon_main.dart
> ex) closes #31, #32 
> 1. バスページ関連のルーターを正義しました。
버스 페이지 관련 라우터를 정의했습니다.
> 2. バスメインページのUIを実装しました。
버스 메인페이지의 UI를 구현하였습니다.
> 3. バスQRページのUIを実装しました。
버스 QR페이지의 UI를 구현하였습니다.
> 4. 美容室メインページでドロワーを追加しました。
미용실 메인페이지에 drawer를 추가하였습니다.
> 
> Design: バスメインページUI実装 その他

- lib/auth/presentation/pages/login_google_domestic_students.dart
- lib/auth/presentation/pages/login_standard_foreign_international.dart
- lib/auth/presentation/widgets/auth_text_form_field.dart
- lib/auth/presentation/widgets/google_login_button.dart
> なし
> 1.  パスワードのマスキングを追加しました。패스워드 마스킹을 추가하였습니다.
> 2. TextButtonのテキストを変更しました。 텍스트 버튼의 텍스트를 변경 했습니다. (문구 변경)
> 3. Googleログインのボタンで機種によるオーバーフロー発生が確認され、Padding値の調整しました。
구글 로그인 버튼에서 기종에 따른 overflow가 발생되는 것이 확인되어, Padding 수치를 조정하였습니다.
> 
> Fix: 機種によるオーバーフロー発生でPadding値の調整

- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/meeting_room.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
- lib/salon(admin)/domain/usecases/calendar_builders_weekday.dart
- lib/salon(admin)/presentation/pages/admin_salon_main.dart
- lib/shared/widgets/CustomSingleChildScrollView.dart
> X
> - アプバーの直下に位置するウィジェットがあり、画面の上部にいる場合（スクロールしていない場合）に上にスクロールできないようにするために、CustomSingleChildScrollViewを作成しました。
appbar의 바로 밑에 위치하고 있는 위젯이 있어, 화면 상단에 있을 경우(스크롤을 하지 않았을 경우)에는 위로 스크롤을 하는 것을 방지하고자, CustomSingleChildScrollView를 만들었습니다.
> - このウィジェットを適用すると、画面の上部では上にスクロールが防止され、下にスクロールした時点で上にスクロールできるようになります。
해당 위젯을 적용하면, 상단에 있을 경우 위쪽 스크롤이 방지되고, 아래로 스크롤한 시점부터 위로 스크롤 할 수 있도록 활성화됩니다.
> 
> Feat: トップスクロールを防ぐためのCustomSingleChildScrollViewウィジェットの実装

- lib/salon(admin)/presentation/pages/admin_salon_booking.dart
- lib/salon(admin)/presentation/pages/admin_salon_main.dart
- lib/salon(admin)/presentation/widgets/booking_box.dart
- lib/salon(admin)/presentation/widgets/booking_calendar.dart
- lib/salon/presentaion/pages/salon_booking.dart
> #61 
> 1. 予約管理ページのUIを実装しました。（管理者向け） 예약 관리 페이지 UI를 구현했습니다.
> 2. 美容室管理者メインページの「もっと見る」ボタンの位置を変更しました。 미용실 관리자 메인 페이지의 더보기 버튼의 위치를 변경했습니다.
> 
> Design: 予約管理ページのUI実装

- lib/salon(admin)/presentation/pages/admin_salon_main.dart
- lib/salon(admin)/presentation/pages/admin_salon_price_list.dart
- lib/salon(admin)/presentation/widgets/booking_box.dart
- lib/salon(admin)/presentation/widgets/edit_service_modal.dart
- lib/salon(admin)/presentation/widgets/service_tabbar.dart
> #62 
> 1. 価格表ページのUIを実装しました。（管理者向け） 관리자용 가격표 페이지 UI를 구현했습니다.
> 2. admin_salon_mainにあるボタンのonPressedにNavigatorを追加しました。 admin_salon_main에 위치한 버튼의 onPressed에 네비게이터를 추가하였습니다. 
> 3. admin_salon_mainにあるボタンのスタイルを修正しました。 admin_salon_main에 있는 버튼의 스타일을 변경하였습니다.
> 
> Design: 美容院の価格表ページのUI実装(管理者向け) 

- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/domain/usecases/register_usecase.dart
- lib/auth/presentation/pages/international_registration.dart
> #59 
> 会員登録ページ(語学堂学生用)API通信ロジックを実装しました。（+ ユースケース、データソース、会員登録ボタンのロジック）
회원가입 페이지(어학당 학생용) API 통신 로직을 구현하였습니다. (+ usecase, datasource, 회원가입 버튼 클릭 시 로직 처리)
> 
> Feat: 会員登録ページ(語学堂学生用)API通信ロジックの実装

- lib/shared/widgets/as_image_view.dart
- lib/shared/widgets/as_image_view_detail.dart
- 한국어
> 이미지 상세보기에서 사용자가 스와이프를 하여 다음 이미지로 넘어갈 수 있도록 기능을 추가하였습니다.
- 日本語
> 画像詳細表示でユーザーがスワイプして次の画像に移動できるように機能を追加しました。
> 
> Feat: 画像ビュースワイプ機能追加

- lib/as(admin)/presentation/widgets/as_floating_button.dart
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/domain/entities/user.dart
- lib/auth/domain/usecases/detail_usecase.dart
- lib/auth/domain/usecases/login_usecase.dart
- lib/auth/domain/usecases/register_usecase.dart
> #94 
- 한국어
> 1. 로그인 후 페이지 이동 시 뒤로가기 스와이프를 했을 경우, 로그인 페이지로 이동되는 문제가 있어 `Navigator.pushNamed`를 `Navigator.pushNamedAndRemoveUntill`로 변경하여 뒤로가기를 방지하였습니다.
> 2. AS 관리자의 AS 게시글 보기에 있는 플로팅 버튼에서 불필요한 `SpeedDialChild`를 제거하였습니다. (`댓글 작성 SpeedDialChild`를 누르면 댓글 작성 및 상태를 변경할 수 있는 체크 박스 노출)
- 日本語
> 1. ログイン後のページ移動時にバックスワイプした場合、ログインページに移動してしまう問題があったため、`Navigator.pushNamed`を`Navigator.pushNamedAndRemoveUntil`に変更し、戻る動作を防止しました。
> 2. AS管理者のAS掲示板閲覧時のフローティングボタンから不要な`SpeedDialChild`を削除しました。 (`コメント作成のSpeedDialChild`を押すと、コメント作成とステータス変更ができるチェックボックスが表示されます。)
> 
> Fix: Navigator.pushNamedからpushNamedAndRemoveUntilに変更（ログイン後に戻るを防止）

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/domain/usecases/domain_validation_usecase.dart
- lib/auth/presentation/widgets/auth_text_form_field.dart
- lib/auth/presentation/widgets/google_login_button.dart
> ex) #98 
> 한국어
- 1. 학교 이메일이 아닌 구글 이메일의 로그인 방지를 구현하였습니다.
- 2. riverpod 토큰 state 변수에 잘못된 데이터가 관리되고 있어 발견하여 수정하였습니다.
- 3. 비밀번호의 라벨 텍스트를 수정하였습니다.
> 日本語
- 1. 学校のメールではないGoogleメールのログインを防止するように実装しました。
- 2. riverpodトークンのstate変数に誤ったデータが管理されていることが発見され、修正しました。
- 3. パスワードのラベルテキストを修正しました。
> 
> Feat: 学校のメールではないGoogleメールのログイン防止

- lib/as(admin)/presentation/pages/as_main.dart
- lib/salon(admin)/presentation/pages/admin_salon_main.dart
- lib/salon/data/data_sources/price_data_source.dart
- lib/salon/data/models/service.dart
- lib/salon/presentaion/pages/salon_price_list.dart
- lib/salon/presentaion/viewmodels/service_viewmodel.dart
- lib/salon/presentaion/viewmodels/user_selection_viewmodel.dart
- lib/salon/presentaion/widgets/filter_group_botton.dart
- lib/salon/presentaion/widgets/filter_service_list.dart
> #100 
> 한국어
1. 미용실 가격표 페이지의 UI를 개선하였습니다.
2. 미용실 가격표 페이지 관련 API 통신 로직을 작성하였습니다.
- `getCategoryListAPI` : 카테고리 목록을 불러오는 API
- `getServiceListAPI`: 성별과 카테고리 아이디 값을 기반으로 필터링된 서비스 목록을 불러오는 API
3. API 통신으로부터 return 된 값을 가격표 페이지의 UI에 랜더링하기 위해 viewmodel을 작성하였습니다.
- `service_viewmodel.dart` : `FutureProvider.autoDispose.family`를 이용하여 선택 정보를 기반으로 UI에 동적으로 랜더링합니다.
4. API 통신으로 return 된 json 데이터를 Dart 객체로 변환하기 위한 `service` 모델을 작성하였습니다.
5. 관리자 메인 페이지에 등록되어 있던 drawer를 제거하였습니다.
> 일본어
1. 美容室の価格表ページのUIを改善しました。
2. 美容室の価格表ページに関連するAPI通信ロジックを作成しました。
- `getCategoryListAPI`：カテゴリーリストを取得するAPI
- `getServiceListAPI`：性別とカテゴリーIDを基にフィルタリングされたサービスリストを取得するAPI
3. API通信から返された値を価格表ページのUIにレンダリングするために、viewmodelを作成しました。
- `service_viewmodel.dart`：`FutureProvider.autoDispose.family`を使用して、選択情報に基づいてUIに動的にレンダリングします。
4. …
> Feat: 価格表ページのAPI通信ロジック作成

- ios/Podfile.lock
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/domain/entities/user.dart
- lib/auth/presentation/viewmodels/user_viewmodel.dart
- lib/main.dart
- lib/salon/data/data_sources/booking_data_source.dart
- lib/salon/data/data_sources/notice_data_source.dart
- lib/salon/data/models/business_hours.dart
- lib/salon/data/models/notice.dart
- lib/salon/domain/usecases/reservation_usecase.dart
- lib/salon/presentaion/pages/salon_main.dart
- lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
- lib/salon/presentaion/viewmodels/booking_select_list_viewmodel.dart
- lib/salon/presentaion/viewmodels/notice_viewmodel.dart
- lib/salon/presentaion/widgets/booking_calendar.dart
- lib/salon/presentaion/widgets/booking_execution_modal.dart
- lib/salon/presentaion/widgets/time_slots_grid.dart
- lib/shared/service/device_info.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> #118 #112
> 한국어
1. 앱 실행 시 디바이스 정보를 읽어오고, 구글 로그인 후 토큰 교환 시에 디바이스 정보를 보내도록 수정하였습니다. (엔티티, viewmodel 수정)
2. 미용실 메인페이지에서 최근에 작성된 공지사항 3건이 보이도록 UI 수정 및, API 통신 로직을 작성하였습니다. (model, viewmodel 작성)
3. 미용실 예약 시 달력에서 날짜를 누르면 그 날짜의 영업 시간이 나오도록 API 교체 후 관련 로직 및 위젯들을 수정하였습니다. 
> 日本語
1. アプリ実行時にデバイス情報を読み込み、Googleログイン後のトークン交換時にデバイス情報を送信するように変更しました。（エンティティ、ビューモデルを修正）
2. 美容室のメインページで、最近投稿されたお知らせ3件が表示されるようにUIを修正し、API通信ロジックを作成しました。（モデル、ビューモデルを作成）
3. 美容室の予約時にカレンダーから日付を選ぶと、その日の営業時間が表示されるようにAPIを交換後、関連ロジックおよびウィジェットを修正しました。
> 
> Refactor: 特定の日付の営業時間を読み込むようにAPIをリファクタリング

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/register_data_source.dart
- lib/main.dart
- lib/salon/data/data_sources/booking_data_source.dart
- lib/salon/data/data_sources/notice_data_source.dart
- lib/shared/service/auth_service.dart
- lib/shared/service/token_decoder.dart
- pubspec.lock
- pubspec.yaml
> #121
> 한국어
- 액세스 토큰의 만료 여부를 파악하여, 만료됐을 시 `api/refresh`로 통신하는 로직을 구현하였습니다.
> 日本語
- アクセストークンの有効期限の有無を確認し、期限が切れた場合にapi/refreshで通信するロジックを実装しました。
> 버스 API 연결 작업이 끝나면 테스트 예정입니다.
> Feat: アクセストークンの期限切れに伴うリフレッシュトークンの送信ロジックの実装

- lib/auth/data/data_resources/login_data_source.dart
- lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
- lib/salon/presentaion/viewmodels/unique_key_viewmodel.dart
- lib/salon/presentaion/widgets/admin/add_service_modal.dart
- lib/salon/presentaion/widgets/admin/category_dropdown.dart
- lib/salon/presentaion/widgets/admin/edit_service_button.dart
> #139 
> 한국어
1. 미용실 관리자 가격표 페이지의 서비스 등록 API 통신 로직을 작성하였습니다. (이와 관련된 커스텀 위젯들 작성)
2. 서비스 Provider에 활용하던 UniqueKey 변수의 유연한 활용을 위해 변수 선언 위치를 상위 위젯으로 이동했습니다.
3. 리프레시 토큰 교환 API 통신 로직 내 오탈자를 발견하여 수정하였습니다.
> 日本語
1. 美容室管理者の価格表ページにおけるサービス登録のAPI通信ロジックを作成しました。（関連するカスタムウィジェットも作成）
2. サービスProviderに活用していたUniqueKey変数の柔軟な活用のため、変数宣言位置を親ウィジェットに移動しました。
3. リフレッシュトークン交換のAPI通信ロジック内、誤字を発見して修正しました。
리뷰 작성 후 계속 머지 안 하고 있으면 머지 부탁드립니다
> Feat: 美容室の価格表サービスを追加するAPI通信ロジックの実装

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/salon/data/data_sources/admin/admin_category_data_source.dart
- lib/salon/domain/entities/category.dart
- lib/salon/domain/usecases/admin_category_usecase.dart
- lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
- lib/salon/presentaion/pages/salon_booking_step_one.dart
- lib/salon/presentaion/pages/salon_price_list.dart
- lib/salon/presentaion/widgets/admin/add_category_modal.dart
- lib/salon/presentaion/widgets/admin/edit_category_modal.dart
- lib/salon/presentaion/widgets/filter_group_botton.dart
> #138
> 한국어
1. 미용실 관리자 가격표 페이지에 카테고리 등록, 수정, 삭제 API 통신 로직을 작성하였습니다.
2. 기능 확장성 문제로 가격표 페이지의 카테고리 버튼 구현에 사용된 `group_button2` 패키지를 제거하고 `ElevatedButton` 위젯으로 교체하였습니다.
3. 미용실 관리자 가격표 페이지 카테고리 API 통신과 관련된 커스텀 위젯을 구현하였습니다.
> 日本語
1. 美容室管理者の価格表ページにカテゴリー登録、修正、削除のAPI通信ロジックを作成しました。
2. 機能拡張性の問題で価格表ページのカテゴリーボタン実装に使用された`group_button2`パッケージを削除し、`ElevatedButton`ウィジェットに置き換えました。
3. 美容室管理者の価格表ページのカテゴリーAPI通信に関連するカスタムウィジェットを実装しました。
> 
> Feat: 美容室管理者カテゴリー関連API通信ロジックの作成

- lib/as(admin)/data/data_sources/as_data_source.dart
- lib/as(admin)/data/data_sources/as_status_data_source.dart
- lib/as(admin)/data/models/as_comment.dart
- lib/as(admin)/domain/usecases/as_status_usecase.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- lib/as(admin)/presentation/viewmodels/as_viewmodel.dart
- lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
- lib/auth/presentation/viewmodels/privilege_viewmodel.dart
- lib/main.dart
- lib/shared/service/auth_service.dart
- lib/shared/service/interceptor.dart
- lib/shared/widgets/as_comment_box.dart
- lib/shared/widgets/base_appbar.dart
> #192 
> 한국어
1. Dio 인터셉터에 토큰 유무 처리, Form Data 헤더 설정을 하였습니다. (기본 헤더는 `application/json`로 설정되어 있음)
2. AS 관리자 페이지 관련 API 로직의 리팩토링이 이루어졌습니다. (AS 댓글 관련 API, 상태 변경 API, AS 리스트 반환 API)
3. 관리자 관련 로직의 일부 수정이 이루어졌습니다.
> 日本語
1. Dio インターセプターにトークンの有無に応じた処理とForm Dataヘッダーの設定を行いました。（デフォルトヘッダーは`application/json`に設定されています。）
2. AS管理者ページ関連のAPIロジックのリファクタリングが行われました。（ASコメント関連API、ステータス変更API、ASリスト返却API）
3. 管理者関連のロジックの一部が修正されました。 
> 
> Feat: トークンの有無に応じた処理、ヘッダー設定ロジックの追加

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/data/data_resources/reset_password_data_source.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/domain/entities/user.dart
- lib/auth/domain/usecases/detail_usecase.dart
- lib/auth/domain/usecases/reset_password_new_usecase.dart
- lib/auth/domain/usecases/reset_password_verify_code_usecase.dart
- lib/auth/domain/usecases/update_usecase.dart
- lib/auth/presentation/pages/new_password_update.dart
- lib/auth/presentation/widgets/international_admin_login_form.dart
- lib/dashboard/data/data_sources/urgent_data_source.dart
- lib/dashboard/presentaion/viewmodels/urgent_viewmodel.dart
- lib/routes/app_routes.dart
- lib/shared/service/interceptor.dart
> #190 #177 
> 한국어
1. Auth 관련 일부 API 로직에 dio 인터셉터로 로직 교체하였습니다.
2. 비밀번호 재설정 로직을 구현하였습니다.
3. 최근 1건 공지 위젯을 수정하였습니다
4. dio 인터셉터의 401 Unauthorized 에러 처리 부분을 개선하였습니다.
> 日本語
1. 認証関連の一部APIロジックをdioインターセプターで置き換えました。
2. パスワードリセットロジックを実装しました。
3. 最近1件のお知らせウィジェットを修正しました。
4. dioインターセプターの401 Unauthorizedエラー処理を改善しました。
> 
> Feat: パスワードリセットロジックの実装

- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/reset_password_data_source.dart
- lib/salon/presentaion/viewmodels/category_viewmodel.dart
> X
> 한국어
1. 토큰 교체 로직 내 JSON 키값을 변경하였습니다.
2. 비밀번호 초기화 API의 엔드포인트를 수정하였습니다.
> 日本語
1. トークン交換ロジック内のJSONキー値を変更しました。
2. パスワードリセットAPIのエンドポイントを修正しました。
> 
> Fix: リフレッシュトークンのJSON返却キー値の修正

- lib/as(admin)/presentation/pages/as_detail.dart
- lib/auth/data/data_resources/logout_data_source.dart
- lib/shared/widgets/bottom_navigation_bar.dart
> X
> 한국어
1. BottomNavigationBar의 홈 버튼을 눌렀을 경우, AuthService 클래스의 getInitialRoute()를 통하여 기본 라우터를 불러올 수 있도록 수정하였습니다.
2. 로그아웃 API 엔드포인트 변경에 따른 로직 수정이 이루어졌습니다.
> 日本語
1. BottomNavigationBarのホームボタンを押した場合、AuthServiceクラスのgetInitialRoute()を通じてデフォルトルーターを呼び出せるように修正しました。
2. ログアウトAPIエンドポイントの変更に伴うロジックの修正が行われました。
> 
> Refactor: BottomNavigationBarのHomeボタン修正

- lib/auth/data/data_resources/login_data_source.dart
- lib/main.dart
- lib/shared/service/interceptor.dart
- lib/shared/service/token_refresh_manager.dart
> X
> 한국어
1. 여러 API가 동시 호출될 때 액세스 토큰 요청 API가 여러 번 호출되는 버그를 발견하여, 토큰을 효율적으로 관리하기 위해 싱글톤 클래스를 구현했습니다. (새 토큰이 획득될 때까지 대기 중인 요청을 큐에 넣음으로써 중복 토큰 갱신 작업을 방지, 토큰 갱신을 기다리는 요청을 보관하기 위해 Completer 활용)
2. 관리자 로그인 API와 액세스 토큰 요청 API가 인터셉터 적용이 되지 않은 것을 확인하여 코드 리팩토링이 진행되었습니다.
> 日本語
1. 複数のAPIが同時に呼び出される際に、アクセストークンの要求APIが複数回呼び出されるバグを発見し、トークンを効率的に管理するためにシングルトンクラスを実装しました。 (新しいトークンが取得されるまで待機中の要求をキューに入れることで、重複したトークン更新作業を防ぎ、トークン更新を待機している要求を保持するためにCompleterを活用)
2. 管理者ログインAPIとアクセストークン要求APIにインターセプターが適用されていないことが確認されたため、コードのリファクタリングが行われました。
> 
> Feat: トークン中央管理シングルトンクラスの実装

- lib/administration/data/data_sources/notice_data_source.dart
- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/notice_detail_page.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/bus/presentaion/pages/bus_main.dart
- lib/routes/app_routes.dart
- lib/salon/presentaion/pages/admin/admin_salon_main.dart
- lib/salon/presentaion/pages/salon_main.dart
- lib/shared/service/navigate_and_remove_until.dart
> X
> 한국어
1. 공지사항 상세보기 페이지 라우터 분리 및 공지사항 위젯과 연결하였습니다.
2. 관리자 로그인 로직 내 jsoonDecode 키워드를 제거하였습니다.
> 일본어
1. お知らせ詳細ページのルーターを分離し、お知らせウィジェットと接続しました。
2. 管理者ログインのjsonDecodeキーワードを削除しました。
> 
> Feat: お知らせ詳細ページのルーターを分離及びお知らせウィジェットと接続

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/logout_data_source.dart
- lib/firebase_api.dart
- lib/main.dart
- lib/routes/app_routes.dart
- lib/setting/data/data_sources/fcm_token_datasource.dart
- lib/setting/presentation/pages/setting_page.dart
- lib/shared/service/auth_service.dart
> X
> 한국어
1. 로그인 시 FCM 토큰을 서버로 전송하는 로직을 추가하였습니다. (일반 유저 로그인, 구글 로그인, 관리자 로그인 / 자동로그인인 경우에는, 어플 접속 시 FCM 재전송되도록 함)
2. 설정 페이지 파일을 이동하였습니다.
> 日本語
1. ログイン時にFCMトークンをサーバーへ送信するロジックを追加しました。（一般ユーザーログイン、Googleログイン、管理者ログイン/自動ログインの場合、アプリにアクセスするたびにFCMが再送信されるように設定）
2. 設定ページのファイルを移動しました。
> 
> Feat: ログイン時にFCMトークンをサーバーに送信するロジックを追加

- android/app/build.gradle
- android/build.gradle
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/models/user.dart
- lib/auth/presentation/pages/update_user.dart
- lib/firebase_api.dart
- lib/main.dart
- lib/salon/presentaion/widgets/filter_service_list.dart
- lib/setting/data/data_sources/fcm_token_datasource.dart
- lib/setting/presentation/pages/setting_page.dart
- lib/shared/service/auth_service.dart
- lib/shared/service/notification_service.dart
- lib/shared/widgets/as_card.dart
- lib/shared/widgets/base_drawer.dart
- lib/shared/widgets/bottom_navigation_bar.dart
- pubspec.lock
> X
> 한국어
1. 푸쉬 알림(FCM) 로직을 일부 수정하였습니다.
2. 로그인 시 `fcm_token`, `push_enabled` 추가 반환에 따라 User 모델을 수정하였습니다.
3. 정보 수정 페이지 내 전화번호 전송 시 하이픈을 제거하는 로직이 누락되어 추가하였습니다.
4. 그 외 불필요한 코드 및 로직 개선이 일부 이루어졌습니다.
> 日本語
1. プッシュ通知（FCM）ロジックを一部修正しました。
2. ログイン時に`fcm_token`と`push_enabled`の追加返却に合わせて、ユーザーモデルを修正しました。
3. 情報修正ページ内で電話番号送信時にハイフンを削除するロジックが欠けていたため、追加しました。
4. その他、不要なコードとロジックの改善が一部行われました。
> 
> Refactor: プッシュ通知（FCM）の設定一部変更

- lib/administration/data/data_sources/sleepover_data_source.dart
- lib/administration/presentaion/pages/meeting_room_main.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/as(admin)/data/data_sources/as_comment_data_source.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- lib/dashboard/presentaion/pages/dashboard_main.dart
- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
- lib/salon/data/data_sources/admin/admin_reservation_data_source.dart
- lib/salon/presentaion/widgets/time_slots_grid.dart
- pubspec.lock
> X
> 한국어
- 메인 대쉬보드에 있는 버튼 네비게이터에 MediaQuery를 적용하였습니다. (특정 디바이스에서 호환이 안 되어 버튼이 이탈하는 문제 수정)
- 미용실 예약 시 영업 시간 슬롯 버튼의 UI를 변경하였습니다.
- 회의실 예약 시 예외처리 버그를 발견하여 수정하였습니다.
- 그 외, 모달 디자인 통일 작업이 이루어졌습니다.
> 일본어
- メインダッシュボードのボタンナビゲーターにMediaQueryを適用しました。（特定のデバイスで互換性がなく、ボタンがずれる問題を修正）
- 美容室予約時の営業時間スロットボタンのUIを変更しました。
- 会議室予約時のエラーハンドリングのバグを発見し、修正しました。
- その他、モーダルデザインの統一作業を行いました。
> 
> Fix: メインダッシュボードのボタンナビゲーターにメディアクエリを適用
