Shining-Jicheon-Stars/yjg-dart-flutter-frontend

- lib/theme/app_theme.dart
- lib/theme/pallete.dart
- lib/theme/theme.dart
> 해당 없음
> 1. 어플리케이션 통일성을 위해 pallete, theme 파일을 구성하였습니다.
> 2. background color, appbar color는 theme 파일에 설정하였으니 참고하여 사용해 주시고, theme 파일에 설정된 대로 자동적으로 적용이 되니 해당 스타일링 코드는 지워주셔도 됩니다.
> 3.  그 외 컬러는 pallete.dart 파일 확인 후 참고하셔셔 Pallete class import 해서 사용하시면 됩니다.
> 추가적인 색상 지정 및 테마 지정이 필요할 경우 말씀해 주세요.
> Design: Designating the Default Theme for the Application

- lib/main.dart
- lib/screens/restaurant/menu_list.dart
- pubspec.lock
- pubspec.yaml
> Feat: メニューリスト

- lib/screens/restaurant/menu_list.dart
> Feat : メニューリトの変更

- lib/main.dart
- lib/screens/restaurant/menu_list.dart
- lib/screens/restaurant/restaurant_main.dart
- lib/widgets/move_button.dart
> Feat: MoveButton

- lib/common/mini_rounded_box.dart
- lib/screens/dashboard/dashboard_main.dart
- lib/screens/dashboard/rounded_box.dart
- lib/widgets/base_appbar.dart
> 1. ナビゲーションドロワーのアイコンを追加しました。(drawer 아이콘을 추가했습니다.)
　2. ウィジェットのheightの高さを修正しました。 (특정 위젯의 height 값 수정하였습니다.)
　3. 不要なウィジェットとプロパティの削除しました。(필요없는 위젯과 속성을 제거하였습니다.)
> 
> Design: ナビゲーションドロワーのアイコン追加　その他２

- lib/screens/dashboard/dashboard_main.dart
- lib/widgets/base_drawer.dart
- pubspec.lock
- pubspec.yaml
> 1. ナビゲーションドロワーのUIを作りました。(drawer의 ui를 구현하였습니다.)
> 2. 「dotted_line」というパッケージが追加されました。 (dotted_line 패키지가 추가되었습니다.)
> 
> Design: ナビゲーションドロワーUI

- lib/widgets/move_button.dart
> BoxShadowのwithOpacityプロパティを追加しました。(BoxShadow 위젯의 withOpacity 속성을 추가했습니다.)
> 
> Design: 不透明度プロパティ(withOpacity)追加

- lib/screens/restaurant/weekend_meal.dart
- pubspec.lock
- pubspec.yaml
> Feat: 週末の食事ページ

- lib/common/blue_main_rounded_box.dart
- lib/common/notice_box.dart
- lib/common/white_main_rounded_box.dart
- lib/main.dart
- lib/screens/salon/salon_main.dart
> 1. 美容室ページのルーティングを定義しました。(미용실 페이지 라우팅 정의하였습니다.)
> 2. 様々な機能のメインページで使用されるリユーザブルウィジェットを実装しました。 (여러 메인페이지에서 사용될 리유저블 위젯을 구현했습니다.)
> 3. 美容室のメインページUIを実装しました。(미용실 메인 페이지 ui를 구현했습니다.)
> 4. 美容室のメインページに入るお知らせウィジェットを実装しました。 (미용실 메인페이지에 들어가는 공지사항 위젯을 구현하였습니다.)
> 
> Design:  美容室ページ関連のUI実装

- lib/main.dart
- lib/screens/dashboard/dashboard_main.dart
- lib/screens/salon/salon_main.dart
- lib/widgets/base_appbar.dart
> 1. 'price_list'ルーターを追加しました。('price_list' 라우터를 추가했습니다.)
> 2. appbarの通知アイコンをoutlineで変更しました。 (appbar의 알림 아이콘을 outline으로 변경했습니다.)
> 3. 'DashboardMain'のContainerウィジェットをSizedBoxウィジェットで変更しました。 (DashboardMain의 Container 위젯을 SizedBox로 변경했습니다.)
> 
> Chore: 'price_list'ルーターの追加　その他　２

- assets/test.json
- lib/screens/salon/Price.dart
- lib/screens/salon/multi_select.dart
- lib/screens/salon/salon_price_list.dart
- pubspec.lock
- pubspec.yaml
> 1. 料金表ページのUIを実装しました。
>  가격표 페이지의 UI를 구현하였습니다.
> 2. 料金表ページのフィルタリングテストのため、ダミーデータのJSONファイルを作成し、それをマッピングした「Price」モデルを作成しました。
>  가격표 페이지의 필터링 테스트를 위해, 더미 데이터 JSON 파일을 작성하고, 그를 매핑한 Price 모델을 만들었습니다.
> 3. 「multi_select」パッケージを利用して、複数選択が可能なフィルタリングウィジェットを実装しました。
> 'multi_select' 패키지를 이용해서, 다중 선택이 가능한 필터링 위젯을 구현했습니다.
> 
> Design: 美容室の料金表ページUI実装　その他４

- lib/main.dart
- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/restaurant_main.dart
> Feat: 食事申込ページ

- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/menu_list.dart
- lib/screens/restaurant/restaurant_main.dart
- lib/screens/restaurant/weekend_meal.dart
> 一部ページにドロワーを追加しました。（restaurant関連のページ）
- 일부 페이지에 drawer를 추가했습니다. (식수 관련 페이지)
> 
> Design: ドロワー追加

- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/weekend_meal.dart
> Feat: 週末の飲料水のページの申請によってページを異なって見せる

- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/weekend_meal.dart
> Feat: 食事申込ページメニューオプションバーを追加

- lib/theme/theme.dart
> theme.dart内のexportパスの誤字を修正しました。(theme.dart 파일 내 export 경로 수정하였습니다.)
> 
> Chore: theme.dart内のexportパスの誤字を修正

- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/weekend_meal.dart
> Fix: alert クローズエラーの修正

- lib/main.dart
- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/meal_qr.dart
- lib/screens/restaurant/restaurant_main.dart
- pubspec.lock
- pubspec.yaml
> Feat: 食事QRページを追加

- lib/screens/restaurant/meal_application.dart
- lib/screens/restaurant/meal_qr.dart
- lib/screens/restaurant/weekend_meal.dart
> Fix :項目を選択しなかったときのエラーの修正

- lib/main.dart
- lib/screens/admin/admin_main.dart
- lib/screens/restaurant/restaurant_main.dart
> Feat: 行政メインページの追加

- analysis_options.yaml
- lib/main.dart
- lib/screens/bus/bus_dropdown_button.dart
- lib/screens/bus/bus_qr.dart
- lib/screens/bus/bus_schedule.dart
- lib/screens/bus/bus_timeline.dart
- lib/screens/bus/bus_timetable.dart
- pubspec.yaml
> ex) #33 
> 1. 時刻表ページのUIを実装しました。
버스 시간표 페이지의 UI를 구현했습니다.
> 2. 時刻表ページに入るウィジェットを実装しました。（バスタイムライン、ドロップダウンボタン、時刻表）
시간표 페이지에 들어가는 위젯들을 구현했습니다. (버스 타임라인, 드롭다운 버튼, 시간표)
> 3. dropdown_button2パッケージを追加しました。
dropdown_button2 패키지를 추가하였습니다.
> 4. 誤字を発見して修正しました。
오탈자를 발견해서, 수정했습니다.
> 5. 時刻表ページのルーターを定義しました。
시간표 페이지 라우터를 정의했습니다.
> 
> Design: バスの時刻表UIの実装

- lib/main.dart
- lib/screens/admin/admin_main.dart
- lib/screens/admin/notice.dart
- lib/screens/restaurant/restaurant_main.dart
- lib/widgets/move_button.dart
- pubspec.lock
- pubspec.yaml
> Feat: お知らせ ページ

- lib/salon/presentaion/pages/salon_booking.dart
- lib/salon/presentaion/widgets/booking_calendar.dart
- lib/salon/presentaion/widgets/booking_next_button.dart
- lib/salon/presentaion/widgets/booking_service_select.dart
> ex) #34 
> 美容室予約ページのUIを実装しました。 미용실 페이지 UI 구현하였습니다.
> 
> Design: 美容室予約UI実装

- lib/salon/presentaion/pages/salon_price_list.dart
> salon_price_list.dartのインポートパスを修正しました。
> 
> Chore: インポートパスの修正

- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/administration/presentaion/widget/sleepover_widget.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
> Feat: 外泊申請ページ

- .github/CODEOWNERS
> ex) X
> 자동 리뷰어 등록을 위한 CODEOWNERS 파일 생성
> 
> Feat: CODEOWNERS生成

- lib/auth/presentation/pages/international_registration_step1.dart
- lib/auth/presentation/pages/international_registration_step2.dart
- lib/auth/presentation/pages/login_google_domestic_students.dart
- lib/auth/presentation/pages/login_standard_foreign_international.dart
> X
> キーボード表示時のオーバーフロー発生によってSingleChildScrollViewウィジェットを追加しました。
키보드 노출 시 overflow 발생에 따라 SingleChildScrollView 위젯을 추가하였습니다.
> 
> Fix: キーボード表示時のオーバーフロー発生によりSingleChildScrollViewウィジェット追加

- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/meeting_room.dart
- lib/administration/presentaion/widget/meeting_room_card.dart
- lib/administration/presentaion/widget/meeting_room_time.dart
- lib/main.dart
> Feat: 会議室ページ

- lib/administration/presentaion/pages/meeting_room.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/pages/sleepover_application.dart
> Fix: 外泊申請インプットウィンドウピクセルエラーを修正

- .github/CODEOWNERS
- .github/auto_assign.yml
- .github/workflows/pr_assignee.yml
> ex) X
> 개인에게 리뷰 할당되도록 CODEOWNERS 수정
> PR assignee 자동 등록 되도록 action 생성
> 
> Chore: CODEOWNERSを修正

- lib/salon(admin)/presentation/pages/admin_salon_main.dart
- lib/salon(admin)/presentation/widgets/main_rounded_box.dart
- lib/salon(admin)/presentation/widgets/main_rounded_box_s.dart
> ex) #60 
>美容室(管理者)メインページのUIを実装しました。　미용실(관리자) 매안 페이지 UI를 구현하였습니다.
> 
> Design: 美容室(管理者)メインページUI実装

- lib/administration/presentaion/pages/meeting_room.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/administration/presentaion/widgets/meeting_room_card.dart
> Fix:  ディレクトリ名の変更

- lib/administration/presentaion/pages/meeting_room.dart
- lib/restaurant/presentaion/pages/meal_qr.dart
> Feat: QRコード一時追加

- android/app/build.gradle
- android/build.gradle
- pubspec.yaml
> Fix: run エラーを修正

- lib/restaurant/presentaion/pages/weekend_meal.dart
- lib/salon(admin)/presentation/widgets/booking_box.dart
- lib/salon(admin)/presentation/widgets/edit_service_modal.dart
- lib/salon(admin)/presentation/widgets/service_tabbar.dart
- lib/salon/data/models/Price.dart
- lib/salon/presentaion/pages/salon_main.dart
- lib/salon/presentaion/widgets/service_tabbar.dart
- lib/shared/widgets/as_card.dart
- lib/shared/widgets/as_image_view.dart
- lib/shared/widgets/base_drawer.dart
- lib/shared/widgets/custom_rounded_button.dart
- lib/shared/widgets/move_button.dart
> #86 
> 코드 정리(관례에 어긋나는 변수, 클래스, 메서드명 수정, child 위젯 이동 등)
> コードの整理（変数、クラス、メソッド名の規約違反の修正、子ウィジェットの移動など）
- 문제 150여개 -> 131개(230227 기준)
- 問題150件から131件へ減少（2023年2月27日基準）
> 
> Refactor: コードフォーマット

- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/presentation/pages/international_registration.dart
- lib/auth/presentation/viewmodels/email_viewmodel.dart
- lib/auth/presentation/widgets/auth_text_form_field.dart
- lib/salon/presentaion/pages/salon_price_list.dart
> ex) #88
> 이메일 중복 검사 버그 수정하였습니다.
> メール重複チェックのバグを修正しました。
> 
> Fix: メール重複チェックロジックの修正

- lib/restaurant/presentaion/pages/meal_application.dart
- 한국어
> submitMealApplication의 API 통신 body의 키 이름 수정 및 riverpod를 통해 user_id를 가져올 수 있도록 수정하였습니다.
- 日本語
> submitMealApplicationのAPI通信のbodyのキー名を修正し、riverpodを通じてuser_idを取得できるように修正しました。
> 
> Fix: submitMealApplicationのbody修正

- android/app/build.gradle
- lib/administration/presentaion/pages/notice.dart
- lib/restaurant/presentaion/pages/meal_application.dart
- pubspec.lock
- pubspec.yaml
> Feat: お知らせページAPI接続

- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/administration/presentaion/widgets/sleepover_widget.dart
> Feat: 外出/外泊申請ページAPI接続

- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/administration/presentaion/widgets/sleepover_widget.dart
> Refactor: APIトークンの設定

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/models/admin_service.dart
- lib/auth/data/models/token_response.dart
- lib/auth/presentation/viewmodels/privilege_viewmodel.dart
- lib/auth/presentation/viewmodels/user_viewmodel.dart
- pubspec.lock
- pubspec.yaml
> #121 
> 한국어
- 로그인(학생, 관리자) API 일부 변경에 따른 datasource와 모델의 리팩토링이 이루어졌습니다. 
- 리프레시 토큰 건은 추후 처리
> 日本語
- ログイン（学生、管理者）APIの一部変更に伴い、datasourceおよびモデルのリファクタリングが行われました。
- リフレッシュトークンに関する件は後ほど対応します。
> 
> Refactor: Token関連のモデル修正

- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/administration/presentaion/widgets/sleepover_widget.dart
> Refactor: APIトークンの変更

- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/as_application.dart
- lib/administration/presentaion/pages/as_page.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- lib/as(admin)/presentation/pages/as_main.dart
- lib/shared/widgets/as_card.dart
- lib/shared/widgets/as_image_view.dart
> AS 페이지 API 연결 (관리자 댓글 제외)
> 
> Feat: ASページAPI接続

- lib/as(admin)/presentation/pages/as_detail.dart
>관리자 댓글이 있어도 날짜가 변경 가능했어서 오류 수정함
> 
> Fix: AS日付修正時のエラー修正

- lib/as(admin)/presentation/widgets/service_requester.dart
> Feat: ASページAPI接続2

- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/logout_data_source.dart
- lib/auth/data/models/admin_service.dart
- lib/auth/presentation/widgets/login_button.dart
- lib/main.dart
- lib/salon/data/data_sources/booking_data_source.dart
- lib/shared/service/auth_service.dart
- lib/shared/service/token_decoder.dart
- lib/shared/widgets/base_appbar.dart
- lib/shared/widgets/base_drawer.dart
> #121 
> 한국어
1. 로그인 관련 로직을 수정하였습니다. (토큰 유효성을 검증하여, 자동로그인 여부와 토큰 만료여부에 따른 로그인 처리 세분화)
2. 로그아웃 로직을 일부 변경하였습니다.
3. 관리자 로그인 관련 모델을 수정하였고, 이에 따라 로그아웃 로직이 일부 변경되었습니다.
> 日本語
1. ログイン関連のロジックを修正しました。(トークンの有効性を検証し、自動ログインの有無とトークンの有効期限によるログイン処理を細分化しました)
2. ログアウトロジックを一部変更しました。
3. 管理者ログイン関連のモデルを修正し、それに伴いログアウトロジックが一部変更されました。
> 
> Refactor: ログインとログアウトのロジック変更

- lib/main.dart
- lib/shared/service/token_decoder.dart
> X
> Null check operator used on a null value 에러를 수정했습니다.
> Null check operator used on a null value エラーを修正しました。
> 
> Fix: Null check operator used on a null value エラー修正

- lib/main.dart
- lib/salon/data/data_sources/admin/admin_service_data_source.dart
- lib/salon/domain/entities/service.dart
- lib/salon/domain/usecases/admin_service_usecase.dart
- lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
- lib/salon/presentaion/widgets/admin/edit_service_button.dart
- lib/salon/presentaion/widgets/admin/edit_service_modal.dart
> #136  #135 
> 한국어
1. 관리자 미용실 가격표 페이지 내 서비스 수정, 삭제 API 통신 로직을 구현하였습니다.
2. 관리자 미용실 가격표 페이지의 UI를 학생이 보는 가격표 페이지와 UI를 통일시키기 위해서, UI의 수정이 이루어졌습니다.
> 일본어
1. 管理者美容室の価格表ページ内でのサービス修正、削除API通信ロジックを実装しました。
2. 管理者の美容室価格表ページのUIを学生が見る価格表ページのUIと統一するため、UIの修正が行われました。
3. 
> 
> Feat: 管理者の美容室サービスの更新、削除API通信ロジックの実装

- lib/as(admin)/presentation/pages/as_detail.dart
- lib/shared/widgets/as_card.dart
> Fix: ASページエラーの修正

- lib/restaurant/presentaion/pages/menu_list.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
>식단표 페이지,식수 메인 오늘의 식단표 부분 API 연동
> 
> Feat: 食事表ページAPI連携

- lib/administration/presentaion/pages/admin_main.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
> 행정 메인에 회의실 예약이 없을 때 카드가 안보여서 수정 함
> 
> Fix: 行政メインページ会議室予約カードエラー訂正

- ios/Runner/Info.plist
> IOS환경에서 카메라,갤러리 튕기는 오류 수정
> 
> Fix: imagePicker IOS環境エラーの修正

- lib/shared/widgets/base_drawer.dart
- lib/shared/widgets/bottom_navigation_bar.dart
> bottom_navigation,drawer 네비게이터 연결
> 
> Refactor: Navigatorの接続

- lib/dashboard/presentaion/widgets/rounded_box.dart
> Refactor: QRボタンのNavigatorの接続

- lib/dashboard/presentaion/widgets/rounded_box.dart
> Fix: Navigatorのアドレスエラーを修正

- lib/administration/presentaion/pages/as_page.dart
- lib/administration/presentaion/pages/meeting_room_main.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/widgets/sleepover_widget.dart
> Refactor: 行政ページデザインの修正

- lib/administration/presentaion/pages/as_application.dart
- lib/administration/presentaion/pages/meeting_room_app.dart
- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/as(admin)/presentation/pages/as_detail.dart
> Refactor: デザイン修正

- lib/administration/presentaion/pages/as_page.dart
> 작업전,작업완료,모두보기로 AS신청내역 카드 필터링
> 
> Feat: 申請履歴のフィルタリング

- lib/restaurant/presentaion/pages/meal_application.dart
> Feat: 学期飲料水申請API接続

- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/domain/entities/user.dart
- lib/auth/domain/usecases/update_usecase.dart
- lib/auth/presentation/pages/update_user.dart
- lib/auth/presentation/viewmodels/user_viewmodel.dart
- lib/auth/presentation/widgets/auth_text_form_field.dart
- lib/main.dart
- lib/setting/setting_page.dart
- lib/shared/widgets/bottom_navigation_bar.dart
- pubspec.lock
- pubspec.yaml
> #113 
> 한국어
1. 개인정보 수정 페이지 UI를 구현하였습니다.
2. 개인정보 수정을 위한 수정 API 로직을 일부 변경하였습니다.
3. 설정 페이지 UI를 구현하였습니다. (세부 기능은 추후 구현 예정)
4. BottomNavigationBar에 설정 페이지 네비게이터를 추가하였습니다.
> 일본어
1. 個人情報編集ページのUIを実装しました。
2. 個人情報の編集のためのAPIロジックを一部変更しました。
3. 設定ページのUIを実装しました。（詳細機能は後ほど実装予定）
4. BottomNavigationBarに設定ページのナビゲータを追加しました。
> 
> Design: 設定ページUI実装

- lib/administration/presentaion/pages/meeting_room_app.dart
> X
> Drawer가 누락되어 있어서 추가합니다.
> 
> Fix: ドロワーの追加

- lib/restaurant/presentaion/pages/menu_list.dart
> Fix: アスペクト比エラーを修正

- ios/.gitignore
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/presentation/widgets/google_login_button.dart
- lib/shared/widgets/base_appbar.dart
> #121 
> 한국어
1. 구글 클라이언트 아이디를 `Config.xcconfig` 파일에 관리하여 `info.plist`에 환경변수로 사용할 수 있도록 설정하였습니다.
2. 구글 로그인 관련 로직을 일부 수정하였습니다.
> 日本語
1. Google クライアントIDを`Config.xcconfig`ファイルで管理し、`info.plist`で環境変数として使用できるように設定しました。
2. Google ログイン関連のロジックを一部修正しました。
> 
> Refactor: Googleログインロジック整理

- lib/salon/presentaion/pages/salon_booking_step_one.dart
- lib/salon/presentaion/pages/salon_booking_step_two.dart
- lib/salon/presentaion/pages/salon_main.dart
- lib/salon/presentaion/pages/salon_my_book.dart
- lib/salon/presentaion/pages/salon_price_list.dart
> X
> 한국어
- Drawer 누락을 수정하였습니다.
> 일본어
- ドロワーの欠落を修正しました。
> 
> Fix: ドロワーの欠落修正

- lib/as(admin)/data/data_sources/as_comment_data_source.dart
- lib/as(admin)/data/models/as_comment.dart
- lib/as(admin)/data/models/as_list.dart
- lib/as(admin)/domain/entities/comment.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- lib/as(admin)/presentation/viewmodels/as_viewmodel.dart
- lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
- lib/as(admin)/presentation/widgets/admin_as_floating_button.dart
- lib/as(admin)/presentation/widgets/as_updating_comment_modal.dart
- lib/as(admin)/presentation/widgets/as_writing_comment_modal.dart
- lib/shared/widgets/as_comment_box.dart
> #172 
> 한국어
1. 댓글 로직 분리에 따라 관련 파일들의 리팩토링이 진행되었습니다.
2. 관리자 여부 확인 로직이 일부 수정되었습니다.
> 일본어
1. コメントロジックの分離に伴い、関連ファイルのリファクタリングが行われました。
2. 管理者かどうかを確認するロジックが一部修正されました。
> 
> Refactor: コメントロジックの分離に伴う関連ファイルのリファクタリング

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/as(admin)/presentation/widgets/service_requester.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> #175 
> 한국어
1. AS 페이지에 있는 전화번호를 누르면 전화로 이동하면서 전화 걸 수 있도록 기능을 구현하였습니다.
2. 위의 기능을 구현하기 위해 `url_launcher` 패키지를 활용하였습니다.
> 日本語
1. ASページにある電話番号をクリックすると、電話に移動して電話をかけられるように機能を実装しました。
2. 上記の機能を実装するために、`url_launcher`パッケージを利用しました。
> 
> Feat: ASページ電話発信機能の実装

- lib/restaurant/presentaion/pages/restaurant_main.dart
> 월~수만 주말식수 버튼 클릭 가능 수정, 주말 식수 신청 인원 뜨게 하기
> 
> Refactor:  API接続と曜日別ボタンを有効にする

- lib/restaurant/presentaion/pages/meal_application.dart
> Refactor: 学期飲料口座番号API接続

- lib/restaurant/presentaion/pages/weekend_meal.dart
> Feat: API接続

- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
> 주말,학기 식수 GET API 수정에 따른 오류 수정
> 
> Fix:  APIの修正によるエラーの修正

- lib/administration/presentaion/pages/meeting_room_app.dart
> Refactor: 外出/外泊重複可能修正

- lib/as(admin)/data/data_sources/as_comment_data_source.dart
- lib/as(admin)/domain/usecases/as_comment_usecase.dart
- lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
- lib/bus/data/data_sources/bus_data_source.dart
- lib/bus/data/data_sources/bus_notice_data_source.dart
- lib/bus/domain/usecases/bus_usecase.dart
- lib/salon/data/data_sources/notice_data_source.dart
- lib/salon/data/data_sources/price_data_source.dart
- lib/salon/data/models/notice.dart
- lib/salon/presentaion/viewmodels/category_viewmodel.dart
- lib/salon/presentaion/viewmodels/service_viewmodel.dart
- lib/shared/service/interceptor.dart
> #193  #196  #192 
> 한국어
1. Dio 인터셉터에 생성자 추가 및 _retry 메서드에 재시도 횟수 관련 로직을 추가하였습니다.
2. AS(Admin) 댓글 API 인터셉터 리팩토링
3. 미용실 가격표 페이지 및 공지사항 위젯 API 인터셉터 리팩토링
4. 버스 API 인터셉터 리팩토링
> 日本語
1. Dioインターセプターにコンストラクタを追加し、_retryメソッドにリトライ回数に関するロジックを追加しました。
2. AS(Admin)コメントAPIインターセプタのリファクタリング
3. 美容室の価格表ページおよび告知ウィジェットAPIインターセプタのリファクタリング
4. バスAPIインターセプタのリファクタリング
> 
> Feat: インターセプターのコンストラクター追加及び_retryメソッドに再試行ロジック追加

- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
> 주말식수, 학기식수 API 연동해서 신청 기간에만 버튼 클릭 가능하게 수정함
> 식수 신청 페이지에서 alert새로 추가해서 넣음
> 
> Feat: 飲料水申請期間のみボタンクリック可能機能

- lib/salon/data/data_sources/admin/admin_service_data_source.dart
- lib/salon/data/data_sources/booking_data_source.dart
- lib/salon/data/data_sources/my_booking_data_source.dart
- lib/salon/data/data_sources/price_data_source.dart
- lib/salon/domain/usecases/admin_service_usecase.dart
- lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
- lib/salon/presentaion/viewmodels/reservations_viewmodel.dart
> #196 #197 
> 한국어
- 미용실 페이지(학생, 관리자) API 전체 로직에 Dio 인터셉터가 적용되었습니다.
> 일본어
- 美容室ページ（学生、管理者）の全てのAPIロジックにDioインターセプターが適用されました。
> 
> Refactor: 美容室ページのAPIロジックにDioインターセプターを適用

- lib/administration/presentaion/pages/notice.dart
- lib/administration/presentaion/pages/notice_detail_page.dart
> Feat: お知らせ詳細ビューページの作成、デザインの変更

- lib/restaurant/presentaion/pages/restaurant_main.dart
> Refactor: 飲料水ボタン2個のローディングデザインを修正

- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
> 주말 식수, 학기 식수 alert 삭제 후 스낵바로 변경,  UI동적 업데이트 되게 수정
> 
> Refactor: 飲料水申請デザイン機能の修正

- lib/administration/presentaion/pages/admin_main.dart
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/logout_data_source.dart
- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/data/data_resources/reset_password_data_source.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/domain/usecases/detail_usecase.dart
- lib/auth/domain/usecases/update_usecase.dart
- lib/auth/presentation/widgets/international_admin_login_form.dart
- lib/bus/domain/usecases/bus_usecase.dart
- lib/dashboard/data/data_sources/urgent_data_source.dart
> #190 
> 한국어
- Auth 관련 API 로직에 Dio 인터셉터가 적용되었습니다.
> 일본어
- Auth関連のAPIロジックにDioインターセプターが適用されました。
> 
> Refactor: Auth関連APIロジックにDioインターセプターを適用

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/presentation/pages/registration_details.dart
- lib/auth/presentation/viewmodels/user_viewmodel.dart
- lib/auth/presentation/widgets/google_login_button.dart
> #179 
> 한국어
- 구글 로그인 최초 시도 시 추가 정보 입력 로직을 수정하였습니다.
> 日本語
- Googleログイン初回試行時に追加情報の入力ロジックを修正しました。
> 
> Fix: Googleログインの追加情報入力のロジックを修正

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/presentation/pages/update_user.dart
> X
> 한국어
- 개인정보 수정 관련 로직을 수정하였습니다.
> 日本語
- 個人情報の修正に関するロジックを修正しました。
> 
> Fix: 個人情報の修正に関するロジックの修正

- lib/administration/presentaion/pages/as_application.dart
- lib/administration/presentaion/pages/as_page.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- pubspec.lock
- pubspec.yaml
> as페이지 달력,수정완료버튼,네비게이터 오류, 스낵바 수정
> 
> Refactor: asページデザインの編集

- lib/restaurant/data/data_sources/meal_reservation_data_source.dart
- lib/restaurant/data/data_sources/menu_data_source.dart
- lib/restaurant/data/data_sources/semester_meal_reservation_data_source.dart
- lib/restaurant/data/data_sources/weekend_meal_reservation_data_source.dart
- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/meal_qr.dart
- lib/restaurant/presentaion/pages/menu_list.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
> #191 
> 한국어
- 식당 페이지에서 사용된 API 로직 전체를 datasource 파일로 분리한 후, dio 인터셉터를 적용하였습니다.
> 일본어
- レストランページで使用されたAPIのロジック全体をデータソースファイルに分離した後、Dioインターセプターを適用しました。
> API 로직 교체 후 작동 테스트는 해 봤는데 혹여나 이상이 있으면 말해주세요.
> Refactor: レストランページAPI全体のデータソース分離およびDioインターセプターの適用

- lib/administration/presentaion/pages/meeting_room_app.dart
- lib/administration/presentaion/pages/meeting_room_main.dart
> - 회의실 예약 달력 크기 수정
- 회의실 예약하기 버튼을 시간 선택하면 뜨게 수정
- 회의실 예약 내역 보기 alert 삭제
- 회의실 예약 완료 스낵바 추가
- 회의실 목록 동적 업데이트
> 
> Refactor: 会議室のページデザインを編集

- lib/administration/data/data_sources/sleepover_data_source.dart
- lib/administration/presentaion/pages/sleepover.dart
- lib/administration/presentaion/widgets/sleepover_widget.dart
- lib/administration/presentaion/widgets/std_as_floating_button.dart
> X
> 한국어
1. 외박/외출 신청 취소 API 로직의 파일 분리 및 dio 인터셉터 적용하였습니다.
2. 외박/외출 신청 관련 modal 중복 호출 버그를 수정하였습니다.
3. `2번`의 모달 디자인을 일부 수정하였습니다.
> 日本語
1. 外泊/外出申請キャンセルAPIのロジックをファイル分割し、dioインターセプターを適用しました。
2. 外泊/外出申請関連のモーダルが重複して呼び出されるバグを修正しました。
3. `2`のモダるのデザインを一部修正しました。
> 
> Refactor: 外泊/外出申請キャンセルAPIロジックファイルの分離およびdioインターセプターの適用

- lib/auth/data/data_resources/register_data_source.dart
- lib/auth/presentation/pages/international_registration.dart
> X
> 한국어
- 이메일 중복 체크 API의 엔드포인트를 수정했습니다.
> 日本語
- メール重複チェックAPIエンドポイントを修正しました。
> 
> Fix: メール重複チェックAPIエンドポイントの修正

- android/.gitignore
- lib/auth/data/data_resources/google_login_data_source.dart
- lib/salon/presentaion/viewmodels/service_viewmodel.dart
- lib/shared/service/token_refresh_manager.dart
> X
> 한국어 
- 안드로이드 환경에서의 구글 로그인 작동 불가 버그를 발견하여 수정하였습니다.
> 日本語
- Android環境でのGoogleログイン動作不可のバグを発見し、修正しました。
> 
> Fix: Android環境のGoogleログイン一部修正

- lib/restaurant/data/data_sources/meal_reservation_data_source.dart
- lib/restaurant/presentaion/pages/restaurant_main.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
> 주말,학기 식수 신청 가능 기간 API에서 넘겨주는 데이터 형식이 변해서 그 형식에 맞게 코드 수정
> 
> Refactor: APIの変更によるコードの修正

- lib/shared/service/auth_service.dart
>X
자동로그인 조건 수정(自動ログイン処理の条件修正)
> 
> Fix: 自動ログイン処理の条件修正

- lib/as(admin)/presentation/widgets/admin_as_floating_button.dart
- lib/auth/data/data_resources/logout_data_source.dart
- lib/auth/domain/usecases/login_usecase.dart
- lib/salon/presentaion/widgets/admin/show_booking_state_modal.dart
- lib/salon/presentaion/widgets/my_booking_modal.dart
> X
> 한국어
1. 누락되어 있던 Confirm 모달을 추가하였습니다.
2. 로그아웃 시 스토리지 정리 방식을 수정하였습니다. (storage.deleteAll()로 교체)
3. 내비게이터 서비스의 파일을 분리하였습니다.
> 일본어
1. 確認モーダルが欠落していたため、追加しました。
2. ログアウト時のストレージの整理方法を変更しました。(storage.deleteAll()に置き換え)
3. ナビゲーターサービスのファイルを分離しました。
> 
> Feat: 確認モーダルを追加

- android/app/build.gradle
> 앱 배포를 위해서 키스토어 추가 후 서명 추가
> 
> Feat: アプリ署名の追加

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/main.dart
- lib/shared/service/auth_service.dart
> X
> 한국어
- 구글 로그인에 자동 로그인을 처리하였습니다.
> 日本語
- Googleログインに自動ログインの処理を行いました。
> 
> Chore: Googleログインの自動ログイン処理

- .gitignore
- android/app/build.gradle
- lib/administration/presentaion/pages/sleepover_application.dart
- lib/restaurant/presentaion/pages/meal_application.dart
- lib/restaurant/presentaion/pages/weekend_meal.dart
- pubspec.lock
> aab 추출을 위한  build파일 수정과 flutter 업데이트에 따른 코드 수정
> 
> Refactor: aabを取得するための設定

- lib/shared/service/auth_service.dart
> X
> 한국어
- initRoute와 관련된 로직을 수정하였습니다.
> 日本語
- initRouteに関するロジックを修正しました。
> 
> Fix: initRoute関連ロジックの修正

- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/as_application.dart
- lib/administration/presentaion/pages/as_page.dart
> 1, too many request 수정
2, as신청 후 네비게이터 오류 수정
> 
> Refactor: asページエラーを修正

- lib/bus/presentaion/pages/bus_schedule.dart
- lib/dashboard/presentaion/pages/dashboard_main.dart
- lib/salon/presentaion/viewmodels/reservations_viewmodel.dart
- lib/salon/presentaion/widgets/my_booking_list.dart
- pubspec.lock
> ex) X
> 버스 페이지 상태 관리 로직 개선
> 미용실 페이지 나의 예약 건 확인 페이지의 리랜더링 오류 해결
> 
> Refactor: 状態管理ロジックの改善

- lib/shared/service/auth_service.dart
> X
- 예외 처리 누락 수정
- 例外処理の漏れを修正
> 
> Fix: 例外処理の漏れを修正

- lib/salon/domain/usecases/reservation_usecase.dart
> Fix: ナビゲーターのエラー修正

- lib/as(admin)/presentation/pages/admin_as_main.dart
- lib/salon/presentaion/widgets/admin/admin_booking_calendar.dart
- lib/salon/presentaion/widgets/my_booking_list.dart
- lib/shared/widgets/mini_rounded_box.dart
> X
> 한국어
1. 데이터 새로고침 기능을 추가하였습니다. (미용실 예약[유저, 관리자], AS[관리자])
2. 메인 대시보드 페이지 내 공지사항 위젯의 텍스트 overflow 버그를 수정하였습니다.
> 日本語
1. データ更新機能を追加しました。(美容室予約[ユーザー、管理者]、AS[管理者])
2. メインダッシュボードページのお知らせウィジェットのテキストオーバーフローバグを修正しました。
> 
> Feat: データ更新機能を追加

- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/profile/AndroidManifest.xml
- lib/administration/data/data_sources/std_as_data_source.dart
- lib/administration/presentaion/pages/as_application.dart
- pubspec.lock
- pubspec.yaml
> Refactor: アプリ配布エラーを修正

- lib/auth/data/data_resources/google_login_data_source.dart
- lib/auth/data/data_resources/login_data_source.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/domain/usecases/detail_usecase.dart
- lib/auth/domain/usecases/update_usecase.dart
- lib/auth/presentation/pages/update_user.dart
- lib/setting/data/data_sources/fcm_token_datasource.dart
- lib/setting/domain/entities/push.dart
- lib/setting/domain/usecases/push_notification_usecase.dart
- lib/setting/presentation/pages/setting_page.dart
- lib/shared/service/snack_bar.dart
> #245 
> 한국어
1. 설정 페이지 내 푸쉬 알림 켜기/끄기 기능을 구현하였습니다.
2. 구글 로그인 로직 내 불필요한 로직을 제거하였습니다.
3. 유저 관련 로직 내 오탈자를 수정하였습니다.
> 일본어
1. 設定ページ内でプッシュ通知のオン/オフ機能を実装しました。
2. Googleログインロジック内の不要なロジックを削除しました。
3. ユーザー関連のロジック内で誤字を修正しました。
> 
> Feat: プッシュ通知のオン/オフ機能の実装

- android/app/build.gradle
- android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
- android/build.gradle
- android/gradle.properties
- lib/main.dart
> Fix: 飲料水QRホームウィジェットのバグ修正

- .gitignore
- android/.gitignore
> X
> gitignore設定 (gitignore 설정)
> 
> Chore: gitignore設定

- android/app/build.gradle
- android/app/src/main/java/yeungjin/global_app/MyAppWidgetProvider.java
- android/app/src/main/java/yeungjin/global_app/MySecondAppWidgetProvider.java
- android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
- lib/main.dart
- pubspec.lock
- pubspec.yaml
>  토큰 값에 따라서 홈 위젯을 클릭 했을 때 연동되는 페이지 다르게 하기
> 
> Refactor: トークン値によるウィジェットページ

- ios/Podfile.lock
- lib/administration/presentaion/pages/admin_main.dart
- lib/administration/presentaion/pages/as_application.dart
- lib/administration/presentaion/pages/as_page.dart
- lib/as(admin)/data/data_sources/as_status_data_source.dart
- lib/as(admin)/presentation/pages/as_detail.dart
- lib/auth/data/data_resources/user_data_source.dart
- lib/auth/domain/usecases/detail_usecase.dart
> Refactor: UI修正

- android/app/build.gradle
- android/app/src/main/java/yeungjin/global_app/MyAppWidgetProvider.java
- android/app/src/main/java/yeungjin/global_app/MySecondAppWidgetProvider.java
- android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
- lib/main.dart
- pubspec.lock
- pubspec.yaml
> Refactor: トークンによるホームウィジェットの修正

- lib/main.dart
> #260 
> localization 추가 (localizationの追加)
> 
> Feat: localization追加
